/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sbc;

import org.apache.jena.query.*;
import org.apache.jena.rdf.model.RDFNode;
import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Crismajovi
 */
public class buscador_semantico extends javax.swing.JFrame {

    /**
     * Creates new form buscador_semantico
     */
    String service = "http://localhost:8890/sparql";
    String defaultGraph = "http://localhost:8890/sbc_proyecto";

    public buscador_semantico() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        select = new javax.swing.JComboBox<>();
        prueba = new javax.swing.JComboBox<>();
        texto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        area1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        ;

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(13, 197, 222));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sistema de Información Académica Científica de UTPL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 30), new java.awt.Color(222, 13, 13))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Avenir Next", 0, 13)); // NOI18N

//        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img.png"))); // NOI18N
        jLabel2.setText("Buscar por ");

        select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Palabra Clave", "Articulos", "Proyectos"}));
        prueba.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Año", "Nombre",}));

        area1.setColumns(20);
        area1.setRows(5);
        jScrollPane1.setViewportView(area1);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jButton1)
                                                .addGap(69, 69, 69)))
                                .addComponent(jLabel3)
                                .addGap(143, 143, 143))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(prueba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        prueba.setVisible(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String item = select.getSelectedItem().toString();
        String nmb = prueba.getSelectedItem().toString();
        System.out.println("````" + item);
        if (texto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "por favor lleno el campo texto");
        } else {
            if (item.equals("Palabra Clave")) {
                verconsulta();
            }
            if (item.equals("Articulos")) {
                String var = texto.getText();

                if (var.equals("nombre")) {

                    verconsulta2();
                }
                if (var.equals("personas")) {

                    verconsulta22();
                }

            }
            if (item.equals("Proyectos")) {
                verconsulta21();
            }

        }
        //verconsulta();

    }//GEN-LAST:event_jButton1ActionPerformed

    public void verconsulta() {

        String prueba = "";
        prueba = String.valueOf(texto.getText());

        area1.setText(" ");
        area1.append("RESULTADO DE BUSQUEDA GENERAL\n");

        String queryString = "PREFIX dbo: <http://dbpedia.org/ontology/>"
                + " PREFIX foaf: <http://xmlns.com/foaf/0.1/>"
                + "SELECT DISTINCT ?o  "
                + "WHERE {"
                + "?s foaf:name ?o "
                + "FILTER regex(?o, '" + prueba + "','i')}";
        System.out.println("primera--------" + queryString);
        pregunta1(queryString);

    }

    public void verconsulta2() {

        area1.append("RESULTADO DE BUSQUEDA NOMBRE DE LOS ARTICULOS -------------\n");

        String queryString = "PREFIX dbo: <http://dbpedia.org/ontology/>"
                + " PREFIX foaf: <http://xmlns.com/foaf/0.1/>"
                + " select  DISTINCT ?o "
                + "where {"
                + " <http://example.org/data/WrittenWork> foaf:name ?o ."
                + "}";

        System.out.println(queryString);
        pregunta1(queryString);

    }

    public void verconsulta22() {

        area1.append("RESULTADO DE BUSQUEDA -------------\n");

        String queryString = "PREFIX dbo: <http://dbpedia.org/ontology/>"
                + " PREFIX foaf: <http://xmlns.com/foaf/0.1/>"
                + " select  DISTINCT ?o "
                + "where {"
                + " <http://example.org/data/Person> foaf:name ?o ."
                + "}";

        System.out.println(queryString);
        pregunta1(queryString);

    }

    public void verconsulta21() {

        area1.append("RESULTADO DE BUSQUEDA NOMBRE DE LOS PROYECTOS -------------\n");

        String queryString = "PREFIX dbo: <http://dbpedia.org/ontology/>"
                + " PREFIX foaf: <http://xmlns.com/foaf/0.1/>"
                + " select  DISTINCT ?o "
                + "where {"
                + " <http://example.org/data/Project> foaf:name ?o ."
                + "}";

        System.out.println(queryString);
        pregunta1(queryString);

    }

    public void pregunta1(String queryString) {

        //QueryExecution qexec1 = QueryExecutionFactory.sparqlService(service, queryString, defaultGraph);
        QueryExecution qexec1 = QueryExecutionFactory.sparqlService(service, queryString);

        ResultSet results = qexec1.execSelect();
        ;
        while (results.hasNext()) {
            System.out.println("''''''''''''''''");
            QuerySolution sol = results.nextSolution();
            RDFNode object = sol.get("S");
            RDFNode subject = sol.get("o");

            System.out.println("--" + subject);
            System.out.println("´´" + object);
            area1.append("---------------------------------------------------------------------" + "\n");
            area1.append(subject.toString() + "\n");

        }
        System.out.close();

    }

    public void pregunta3(String queryString) {
        //QueryExecution qexec1 = QueryExecutionFactory.sparqlService(service, queryString, defaultGraph);
        System.out.println("consulta------" + queryString);
        QueryExecution qexec1 = QueryExecutionFactory.sparqlService(service, queryString);
        ResultSet results = qexec1.execSelect();
        System.out.println("llegoooo");
        while (results.hasNext()) {
            QuerySolution sol = results.nextSolution();
            RDFNode ob = sol.get("ob");
            RDFNode ye = sol.get("ye");
            System.out.println("----------------" + sol.toString());

            area1.append("------------------------------------------------" + "\n");
            area1.append("Nombre del articulo: " + "\n" + ob.toString() + "\n");
            area1.append("------------------------------------------------" + "\n");
            area1.append("Año de publicacion: " + "\n" + ye.toString() + "\n");

        }
        System.out.close();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buscador_semantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buscador_semantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buscador_semantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buscador_semantico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buscador_semantico().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> select;
    private javax.swing.JComboBox<String> prueba;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
